#!/bin/bash
# envsubst へ渡すリテラルな ${VAR} を単一引用で保持する設計のため、
# SC2016（単一引用内は非展開）は意図どおり。ファイル全体で無効化する。
# shellcheck disable=SC2016
set -euo pipefail
cd "$(dirname "$0")"

# 変数定義（X_*/修飾子セット/BRACKET_*/SE_UNDEFINED）は別ファイルへ分離。
# データ＝render-vars.sh / ロジック＝本ファイル。値の編集は render-vars.sh で完結。
# shellcheck source=render-vars.sh
# -x 無しの単体検査では source 先を追えない（CI は plain shellcheck）。
# shellcheck disable=SC1091
. ./render-vars.sh


# ---- skhdrc 生成 → 検証 → デプロイ ----
# 対象は jackielii/skhd.zig (>= v0.1.1 を想定: --start-service は冪等、
# 設定既定パスは ~/.config/skhd/skhdrc、専用の --check/dry-run フラグは無い)。
# source (skhdrc.tmpl) は repo 内、生成物は ~/.config/skhd/skhdrc へ配置。
# 一旦 temp に生成して検証し、OK の時だけデプロイ先へ移動する
# (壊れた設定が稼働中の skhdrc を上書きしない)。
# 注: skhd.zig は重複 binding (同一 "mods - key") をハードエラー扱いにする。
OUT="$HOME/.config/skhd/skhdrc"

# envsubst は指定変数のみ置換 (jq フィルタの $array 等を守るため)。
# X_* は render-vars.sh の全 X_ 変数から自動列挙（重複保守を排除）。X_ 以外
# の置換変数のみ明示。
VARS=""
# 変数名に空白は無いので word-split は意図的。
# shellcheck disable=SC2046
for _n in $(printf '%s\n' "${!X_@}" | sort); do VARS="$VARS \${$_n}"; done
VARS="$VARS \${BRACKET_OPEN} \${BRACKET_CLOSE} \${ULTRA_LL} \${MIRACLE_LM} \${MEGA_RM} \${WONDER_RR}"

tmp=$(mktemp)
trap 'rm -f "$tmp"' EXIT
envsubst "$VARS" < skhdrc.tmpl > "$tmp"

# ---- 未定義キー効果音フォールバックを生成して追記 ----
# 4 修飾子セット (ULTRA_LL/MIRACLE_LM/MEGA_RM/WONDER_RR) × 全 X_ キーを
# 効果音にバインドする。ただし既に実バインド済みの "mods - key" は除外
# (skhd.zig は重複 binding をハードエラーにするため)。除外は手管理せず、
# envsubst 済みの $tmp を走査して自動判定する → 実バインドを足しても無保守。
#
# 既存 binding シグネチャ ("mods - key") を $tmp から収集 (空白は単一化)。
# - 行頭 #/.define/"/] と空行は対象外。app ブロックの `... [` 開始行と
#   `mods - key : cmd` の両形から key までを取り出す。
# bash 3.2 (macOS 既定) には連想配列が無いため改行区切り文字列 + grep -Fxq。
_existing=$(awk '
  { l=$0; sub(/^[ \t]+/,"",l); sub(/[ \t]+$/,"",l)
    if (l=="") next
    c=substr(l,1,1)
    if (c=="#" || c=="\"" || c=="]") next
    if (l ~ /^\.define/) next
    if (l ~ / \[$/)            { s=l; sub(/ \[$/,"",s) }
    else if (index(l," : ")>0) { s=substr(l,1,index(l," : ")-1) }
    else next
    gsub(/[ \t]+/," ",s); sub(/^ /,"",s); sub(/ $/,"",s)
    print s
  }
' "$tmp")

# "mods - key" を修飾子順に依存しない正準形へ畳む。skhd は修飾子を集合
# として扱い重複判定するため、文字列一致だと順序ゆれ (ralt+rctrl vs
# rctrl+ralt) を取りこぼし skhd ハードエラーになる。トークンを sort。
_canon() {
  _ck="${1##* - }"; _cm="${1% - *}"
  _cs=$(printf '%s\n' "$_cm" | tr '+' '\n' \
        | awk '{gsub(/^[ \t]+|[ \t]+$/,"");print}' | sort | tr '\n' ',')
  printf '%s|%s\n' "$_cs" "$_ck"
}

# 既存シグネチャを正準形に畳んだ集合 (順不同で突合できる)。
_existing_norm=$(
  if [ -n "$_existing" ]; then
    printf '%s\n' "$_existing" | while IFS= read -r _e; do
      [ -n "$_e" ] && _canon "$_e"
    done
  fi
)

{
  echo ""
  echo "# ==== AUTO-GENERATED by render.sh: 未定義キー効果音フォールバック ===="
  echo "# 4 修飾子セット × (全 X_ キー − FALLBACK_EXCLUDE_KEYS)。実バインド"
  echo "# 済みは修飾子順を問わず自動除外。手編集しない。"
  # 音量: focusfx(window_focused=0.1) より気持ち大きめ。未定義=想定外操作の
  # 警告フィードバックなので、フォーカス通知より気づきやすくする。
  printf '.define se_undefined : afplay --volume 0.3 "%s" &\n' "$SE_UNDEFINED"
  for _set in ULTRA_LL MIRACLE_LM MEGA_RM WONDER_RR; do
    _mods="${!_set}"                       # 間接展開 (bash 3.2 可)
    # X_ 変数名を安定順で列挙。名前に空白は無いので word-split は意図的。
    # shellcheck disable=SC2046
    for _kn in $(printf '%s\n' "${!X_@}" | sort); do
      # 生成対象から完全除外するキー (例: X_1 = 単押し専用で別バインド)
      case " ${FALLBACK_EXCLUDE_KEYS:-} " in *" $_kn "*) continue ;; esac
      _key="${!_kn}"
      if printf '%s\n' "$_existing_norm" \
         | grep -Fxq -- "$(_canon "$_mods - $_key")"; then
        continue   # 実バインド済み (修飾子順不問): 効果音なし
      fi
      printf '%s - %s : @se_undefined\n' "$_mods" "$_key"
    done
  done
} >> "$tmp"

# skhd.zig に dry-run は無いため短時間だけ起動しパース結果を見る。
# timeout は macOS 標準には無い (coreutils の timeout/gtimeout のみ)。
# probe-skhd.sh と同じ思想で timeout の有無に依存しない: timeout→gtimeout
# があれば使い、無ければ自前 sleep+kill で時間制限する。
# rc=124 は時間切れ (= パース成功し run loop へ到達) を意味し正常。
# それ以外の非0、または診断語を含む出力は不正としデプロイしない。
vout=$(mktemp)
trap 'rm -f "$tmp" "$vout"' EXIT
TO=""
if command -v timeout >/dev/null 2>&1; then TO=timeout
elif command -v gtimeout >/dev/null 2>&1; then TO=gtimeout
fi
if [ -n "$TO" ]; then
    if "$TO" 2 skhd -V -c "$tmp" >"$vout" 2>&1; then rc=0; else rc=$?; fi
else
    # 自前の時間制限: バックグラウンド起動し 2 秒後に kill。
    # 2 秒生存 = パース成功で run loop 到達とみなし rc=124 (time-out 相当)。
    skhd -V -c "$tmp" >"$vout" 2>&1 &
    sp=$!
    sleep 2
    if kill -0 "$sp" 2>/dev/null; then
        kill "$sp" 2>/dev/null || true
        wait "$sp" 2>/dev/null || true
        rc=124
    else
        if wait "$sp" 2>/dev/null; then rc=0; else rc=$?; fi
    fi
fi
out=$(cat "$vout")
diag='error|invalid|unexpected|expected|failed|duplicate'
if { [ "$rc" -ne 0 ] && [ "$rc" -ne 124 ]; } || printf '%s' "$out" | grep -iqE "$diag"; then
    echo "skhdrc parse failed (rc=$rc), NOT deploying:" >&2
    printf '%s\n' "$out" | grep -iE "$diag" >&2 || printf '%s\n' "$out" >&2
    exit 1
fi

mkdir -p "$(dirname "$OUT")"
[ -f "$OUT" ] && cp "$OUT" "$OUT.bak"   # 直前の稼働設定を .bak へ退避
# 注: 検証は mv 前に済むため自動復元はしない。.bak は手動復旧用の置物。
mv "$tmp" "$OUT"
trap - EXIT
# --reload は稼働中インスタンスへのシグナル。未起動時は restart→start で確実に。
skhd --reload 2>/dev/null || skhd --restart-service 2>/dev/null || skhd --start-service
echo "skhdrc deployed to $OUT and reloaded"
